# Core Colors
background            #040807
foreground            #ffffff
selection_foreground  #9aecd8
selection_background  #002c24
cursor                #9aecd8
cursor_text_color     #0e1513

# Regular Colors
color0  #0e1513
color1  #ffd2cc
color2  #c0e0fa
color3  #c7e2d9
color4  #9aecd8
color5  #aacbe4
color6  #b1ccc4
color7  #ffffff

# Bright Colors
color8  #3f4946
color9  #ff5449
color10 #7595ac
color11 #7c968e
color12 #4d9f8d
color13 #223b35
color14 #18394e
color15 #d4dfda
