-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "macOS")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        dim_around = 0.1,
        dim_inactive = true,
        dim_strength = 0.05,
    },
    general = {
        col = {
            active_border = "0xff363535",
        },
    },
    misc = {
        animate_mouse_windowdragging = false,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
end)
